### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mirceaalexandru** [nodezoo/nodezoo-search#45]
Travis tests are failing:

```
CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
```

Please change .travis file so that you will fix these errors. You can take a look here:
https://github.com/Concorda/concorda-server/blob/master/.travis.yml#L11

**Comment by andrewcashmore** [comment]
https://github.com/nodezoo/nodezoo-search/pull/46
